branches:
  - main 

projects:
  LobbyTeleport:
    path: . 
    libs:
      - src 
    php-version: ^8.0 
    pmmp:
      versions:
        - 4.0.0 
    build:
      lint: true 
      model: default 
