
name: LobbyTeleport
main: LobbyTeleport\Main
version: 1.0.0
api: 4.0.0
author: TylernoelYT
commands:
  lobby:
    description: Teleport to the lobby
    usage: /lobby
    permission: lobby.teleport
permissions:
  lobby.teleport:
    default: true

lobby:
  x: 100
  y: 65
  z: 100
